### ISSUE TITLE
Building these?

### ISSUE THREAD

**Issue by AyanamiRei1** [masagrator/NXGameScripts#2]
I wanted to try Monster Hunter Generations Ultimate opus encoder with another Capcom game Ultra Street Fighter 2 since I suspect they'd be about the same.

Here's a sample for USF2 as well.
https://drive.google.com/file/d/1Y9ce6jFPOAwTwB78EWUIkXIs1P8L6vCv/view?usp=sharing

**Comment by masagrator** [comment]
you have cmd.txt as an example how to compile it

This repo isn't meant for total beginners, so if you don't understand what you should do from file alone, then tough luck.
