### ISSUE TITLE
VFS3 (Rhapsody A Musical Adventure)

### ISSUE THREAD

**Issue by Giza** [masagrator/NXGameScripts#3]
Can't you check vfs in the game Rhapsody A Musical Adventure?

I saw your script for Ni no Kuni, but it doesn't work for this game, even though the header and beginnings are very similar. 
Script error:
`Traceback (most recent call last):
  File "D:\Games\Rhapsody.A.Musical.Adventure\Game\VFS_Unpacker.py", line 99, in <module>
    file.seek(StringListOffset, 0)
ValueError: cannot fit 'numpy.uint64' into an offset-sized integer
`

**Comment by masagrator** [comment]
This script is only for VFS using zstd with dictionary libraries - something I have saw nowhere else. So I guess your game uses different type of compressing and everything falls apart.

And I'm not taking requests.
