### ISSUE TITLE
Question about Aonatsu

### ISSUE THREAD

**Issue by Cosetto** [masagrator/NXGameScripts#4]
Can we actually use the disassembler on window version of the game? 
I got this error when trying to decompile the scripts of window version:

> D:\Aonatsu\test\Unpacked>Script_disassembler.py Script
> 00共通01
> 437
> String size check failed! Expected: 2412088575, got 21
> Offset: 0x1f8ec
> 奄ﾉ戻りました

[script.zip](https://github.com/masagrator/NXGameScripts/files/11572467/script.zip)

**Comment by masagrator** [comment]
In current form I don't think so. PC uses Unity while Switch version uses NeXaS. There may be differences in opcodes related to different engines

**Comment by Cosetto** [comment]
> In current form I don't think so. PC uses Unity while Switch version uses NeXaS. There may be differences in opcodes related to different engines

No no, the scripts I sent is from Japanese version which uses Nexas engine too. I'm translating it directly from Japanese version

**Comment by masagrator** [comment]
Then it seems something is off if size check fails. It seems console version has slightly changed opcodes which is nothing new in VN modding scene.

I don't plan to add support for PC as I'm interested only in Nintendo Switch modding.

**Comment by Cosetto** [comment]
It's okay. Since the game has only 3 lines limits, I'm finding a way to move the 4 lines to next message box if possible, and the phone message length too.
