### ISSUE TITLE
Packaging Issue with the file preload_zstd.vfs file - Script VFS_Repacker.py

### ISSUE THREAD

**Issue by Digote** [masagrator/NXGameScripts#6]
I have been working with the game files of Ni no Kuni™ II: Revenant Kingdom PRINCE'S EDITION, specifically versions 1.0 and 1.10.

I noticed that the file's magic corresponds to VFS3, so I used your script to package the files without making any changes. However, when I try to test it on an emulator, it gets stuck in an infinite loop while attempting to load.

I just wanted to report this issue, thank you for the script.

**Print Emulator**
![log](https://github.com/masagrator/NXGameScripts/assets/45742711/9918db02-2efd-4a3b-b2f1-3966b4bc7896)

**Files**
![files](https://github.com/masagrator/NXGameScripts/assets/45742711/45c1867d-f39a-4285-a721-b3d3594283b2)

**Comment by eikun79** [comment]
> I have been working with the game files of Ni no Kuni™ II: Revenant Kingdom PRINCE'S EDITION, specifically versions 1.0 and 1.10.
> 
> I noticed that the file's magic corresponds to VFS3, so I used your script to package the files without making any changes. However, when I try to test it on an emulator, it gets stuck in an infinite loop while attempting to load.
> 
> I just wanted to report this issue, thank you for the script.
> 
> **Print Emulator** ![log](https://private-user-images.githubusercontent.com/45742711/254097718-9918db02-2efd-4a3b-b2f1-3966b4bc7896.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1ODg0NTAsIm5iZiI6MTczNjU4ODE1MCwicGF0aCI6Ii80NTc0MjcxMS8yNTQwOTc3MTgtOTkxOGRiMDItMmVmZC00YTNiLWIyZjEtMzk2NmI0YmM3ODk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTExVDA5MzU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxZjliYWZjYjU3YjA3NjhhMGFhZjIwYTJlZGRjMWU1YTY5ZDQwZDE1YjI2ZGZkZWVhNDY3OGYxNWM3NjgyMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uxFJ0KEa3FSyWYQq7ij5pImK8phwDBKeF3c7ontdk4g)
> 
> **Files** ![files](https://private-user-images.githubusercontent.com/45742711/254097955-45c1867d-f39a-4285-a721-b3d3594283b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1ODg0NTAsIm5iZiI6MTczNjU4ODE1MCwicGF0aCI6Ii80NTc0MjcxMS8yNTQwOTc5NTUtNDVjMTg2N2QtZjM5YS00Mjg1LWE3MjEtYjNkMzU5NDI4M2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTExVDA5MzU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZDZmYTg3OWYyMjc5MDk5ZWYwYjNkNjA0MjljNjJiM2U5ZmRmNTE2YjVmZGFmM2FmNzAzZGRkNzRjYTdjYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.docQ1fkUDL-xQl9yckPDfL9xbVZsnF8_2FZvGYbYORE)


I have the same issue on nintendo switch. Is it resolved?
If it's solved, can you share the information?
